[[librsync]]
arch = "i686"
git-tree-sha1 = "0df4942ccd4d8cf8e5a735ecd83ac46667acbade"
libc = "musl"
os = "linux"

    [[librsync.download]]
    sha256 = "69993925e95e97b9d432f50d0159e760f91d18229a61f222418eead8acb76dc6"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.1+1/librsync.v2.3.1.i686-linux-musl.tar.gz"
[[librsync]]
arch = "aarch64"
git-tree-sha1 = "982912ebd3aeba423eaa1ed86d519471558f363c"
libc = "musl"
os = "linux"

    [[librsync.download]]
    sha256 = "f629f1f9dbc45056f65839a20063afaa86eed71fa9732ddc761246aeaa7e5863"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.1+1/librsync.v2.3.1.aarch64-linux-musl.tar.gz"
[[librsync]]
arch = "i686"
git-tree-sha1 = "018f35ba714c9683ab2fa6fdc0ac8b900f2d167b"
os = "windows"

    [[librsync.download]]
    sha256 = "607b7d629033a046102f8370fe368e67118b04e74d5ac0a43f946e536cf54365"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.1+1/librsync.v2.3.1.i686-w64-mingw32.tar.gz"
[[librsync]]
arch = "x86_64"
git-tree-sha1 = "22bbfc872848832aaf13dc95ed3a73117aed1a7a"
os = "windows"

    [[librsync.download]]
    sha256 = "016b0ed19817ff52a4affc45e2f6b258a360460c4220a088cb5f158f19fc7c99"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.1+1/librsync.v2.3.1.x86_64-w64-mingw32.tar.gz"
[[librsync]]
arch = "armv7l"
git-tree-sha1 = "45c200a5c947c2ee9745ba57c85fc091a41ea4ba"
libc = "glibc"
os = "linux"

    [[librsync.download]]
    sha256 = "e47d10e47ee3dc7f3900c3667cbee96535cb6a8cf3c6ab18e2b50860b656e884"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.1+1/librsync.v2.3.1.armv7l-linux-gnueabihf.tar.gz"
[[librsync]]
arch = "armv7l"
git-tree-sha1 = "60b9cb45e6d8e23c33c38074bce62672da14e5ef"
libc = "musl"
os = "linux"

    [[librsync.download]]
    sha256 = "a2216f49d3823492584dffd8097d4adad215590d4189104e07e23d523b558548"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.1+1/librsync.v2.3.1.armv7l-linux-musleabihf.tar.gz"
[[librsync]]
arch = "i686"
git-tree-sha1 = "77521067d31f9fbfc883b78dd556d500454380d3"
libc = "glibc"
os = "linux"

    [[librsync.download]]
    sha256 = "da2989eb171babe8cbc32061d70c6577b1cf0378f4234bc0fbc56a76fc1e27dd"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.1+1/librsync.v2.3.1.i686-linux-gnu.tar.gz"
[[librsync]]
arch = "x86_64"
git-tree-sha1 = "f4bb7c38f3bc43efdcd51929cc2e529d62561bab"
libc = "glibc"
os = "linux"

    [[librsync.download]]
    sha256 = "e3c0feb6f4add010d87084de6f6d2881c260e5014335d3c15175bc767dc32e37"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.1+1/librsync.v2.3.1.x86_64-linux-gnu.tar.gz"
[[librsync]]
arch = "powerpc64le"
git-tree-sha1 = "ac01163523efe95669279cf9e936be68543dfe38"
libc = "glibc"
os = "linux"

    [[librsync.download]]
    sha256 = "838b8e66aa1cda2762ebe3c72e5c8e12769d3150ff32e843953be944079b9ce5"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.1+1/librsync.v2.3.1.powerpc64le-linux-gnu.tar.gz"
[[librsync]]
arch = "x86_64"
git-tree-sha1 = "7b2102fd41220ce8cac1a450de9107b635ed0b39"
os = "macos"

    [[librsync.download]]
    sha256 = "5e73c2db13974d3c775c10c89885fc343c5877594460256b86318e0310f65c29"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.1+1/librsync.v2.3.1.x86_64-apple-darwin14.tar.gz"
[[librsync]]
arch = "aarch64"
git-tree-sha1 = "72f03e8c6570193774db6ff384fc55b4f8900db4"
libc = "glibc"
os = "linux"

    [[librsync.download]]
    sha256 = "b557d2e85b70880855c96a3883466cda3b9a0bba1e93941c48ed6c4fcb4baef1"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.1+1/librsync.v2.3.1.aarch64-linux-gnu.tar.gz"
[[librsync]]
arch = "x86_64"
git-tree-sha1 = "5a44094ebd28ed8e85c4960e44e6f1cef904e40b"
os = "freebsd"

    [[librsync.download]]
    sha256 = "3505dbe57d7283d1e54303eaf75eab462f24ba887de435946c1554d2a53c6885"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.1+1/librsync.v2.3.1.x86_64-unknown-freebsd11.1.tar.gz"
[[librsync]]
arch = "x86_64"
git-tree-sha1 = "c038a689003dc9bbe872aa13257c5bdc035b8734"
libc = "musl"
os = "linux"

    [[librsync.download]]
    sha256 = "656743353f6f4d6adb8680431afc410ec3acc6dd74c1bd964c73bdbcd98c243b"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.1+1/librsync.v2.3.1.x86_64-linux-musl.tar.gz"
