[[librsync]]
arch = "aarch64"
git-tree-sha1 = "76336942b970e41797f35e4c63d1051295d68ec0"
os = "macos"

    [[librsync.download]]
    sha256 = "746cb566cc2631502bced77f336a790f33f7531d81ed0e6b5a8186e4a93fdac9"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.4+0/librsync.v2.3.4.aarch64-apple-darwin.tar.gz"
[[librsync]]
arch = "aarch64"
git-tree-sha1 = "02937b5d337e6bb53316bb361942c93e5b636501"
libc = "glibc"
os = "linux"

    [[librsync.download]]
    sha256 = "937a3f91f2da383f13d3c464edb586a79fd97a052e233789284070a3627ccb32"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.4+0/librsync.v2.3.4.aarch64-linux-gnu.tar.gz"
[[librsync]]
arch = "aarch64"
git-tree-sha1 = "5bf80a41180cb26117bedfc7c8db0f9c620bbe26"
libc = "musl"
os = "linux"

    [[librsync.download]]
    sha256 = "b5e6ece13dd8adbb5457c673967031cf00dd13194ff59c44323d009c0c227df2"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.4+0/librsync.v2.3.4.aarch64-linux-musl.tar.gz"
[[librsync]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2dfdb5053887f75b7206043a3ce384762f35fee3"
libc = "glibc"
os = "linux"

    [[librsync.download]]
    sha256 = "097f06b29b4f284b069deaa4999d075512b50ed6c2bdaa3b5e3b18a24cdd3ab4"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.4+0/librsync.v2.3.4.armv6l-linux-gnueabihf.tar.gz"
[[librsync]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "032405d31b68a83d389fbd3d9c4e0e39d2addabe"
libc = "musl"
os = "linux"

    [[librsync.download]]
    sha256 = "be02dbc1c617d347e2217c03c7eabcbdcb788bd1f62aafe6611d7a675efb5911"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.4+0/librsync.v2.3.4.armv6l-linux-musleabihf.tar.gz"
[[librsync]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8d8cce193adc74acf140066b00a92b6e996d580d"
libc = "glibc"
os = "linux"

    [[librsync.download]]
    sha256 = "ab8f56bad52b0eafba808ecfaa40a351124c55f9494057ba6fa6b1bf38088b8c"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.4+0/librsync.v2.3.4.armv7l-linux-gnueabihf.tar.gz"
[[librsync]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "43af6cd808f10f1f10baefbb4bc1ae52f5191ed0"
libc = "musl"
os = "linux"

    [[librsync.download]]
    sha256 = "d0767b7d3ddb8ef0bd4e238d8e996426f3236d2737dbf5f6206b25e6fe093177"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.4+0/librsync.v2.3.4.armv7l-linux-musleabihf.tar.gz"
[[librsync]]
arch = "i686"
git-tree-sha1 = "8f906f26421d8d0192d51f9c06dbc3fbec3eb696"
libc = "glibc"
os = "linux"

    [[librsync.download]]
    sha256 = "4a2df319a56f7f634dc1c27c66e09224718d1088c202631e17a34ead16730dcf"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.4+0/librsync.v2.3.4.i686-linux-gnu.tar.gz"
[[librsync]]
arch = "i686"
git-tree-sha1 = "517ef1a4b0f776438062c241789b45db911a40f9"
libc = "musl"
os = "linux"

    [[librsync.download]]
    sha256 = "3b6fa14d6068608cb28580bea55cd7e50306192dde98ca501226ee81a11ddc62"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.4+0/librsync.v2.3.4.i686-linux-musl.tar.gz"
[[librsync]]
arch = "i686"
git-tree-sha1 = "a0a5de3b6543872672b05fdcc1b9380a9f8f11ae"
os = "windows"

    [[librsync.download]]
    sha256 = "6b34ad73ff06c839dafb10289c6cae11b24309c5a402780ab114e09631da8670"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.4+0/librsync.v2.3.4.i686-w64-mingw32.tar.gz"
[[librsync]]
arch = "powerpc64le"
git-tree-sha1 = "f4b166e20505bd911c20c2613908170471221998"
libc = "glibc"
os = "linux"

    [[librsync.download]]
    sha256 = "77cf8cb58ef3d4e6e5ac200e4f193a906e7bdcbf28a5a7272b17d5889ad0cf29"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.4+0/librsync.v2.3.4.powerpc64le-linux-gnu.tar.gz"
[[librsync]]
arch = "x86_64"
git-tree-sha1 = "c08fb664a37dcb5a784dc4c83f62a1a334aff12d"
os = "macos"

    [[librsync.download]]
    sha256 = "4e99ba32ab5e61e30c2c001821fb56b71a7d42fdce1ebe79c35d9f3baf5908f6"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.4+0/librsync.v2.3.4.x86_64-apple-darwin.tar.gz"
[[librsync]]
arch = "x86_64"
git-tree-sha1 = "fd02e01947b0a021678d2ca98dc9336b08e98f55"
libc = "glibc"
os = "linux"

    [[librsync.download]]
    sha256 = "3cb7d1f81f692e7785fc8305f9dcfacab3df0acb8bd6f3912c0b7aa5fa3a0ba1"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.4+0/librsync.v2.3.4.x86_64-linux-gnu.tar.gz"
[[librsync]]
arch = "x86_64"
git-tree-sha1 = "ddd65d9f8551e9992bb511e5cbf7f16612107446"
libc = "musl"
os = "linux"

    [[librsync.download]]
    sha256 = "10b8c8d8b4fe7407829169a60312ba74595f182a82db9e6979a2e0786cca2f4e"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.4+0/librsync.v2.3.4.x86_64-linux-musl.tar.gz"
[[librsync]]
arch = "x86_64"
git-tree-sha1 = "753fec213a14d21d446bd400407ec05b165f8edd"
os = "freebsd"

    [[librsync.download]]
    sha256 = "fac4eda89a6ba74cd1476064a612f84affa983ed2ef8aaac6a49f254ace4f938"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.4+0/librsync.v2.3.4.x86_64-unknown-freebsd.tar.gz"
[[librsync]]
arch = "x86_64"
git-tree-sha1 = "4d00929fa775ed6deebd0268cc255a8dd2d25740"
os = "windows"

    [[librsync.download]]
    sha256 = "c1f51c9a1af7063a14f99dd3c506665b13039f8465968a6203739e03f932c053"
    url = "https://github.com/JuliaBinaryWrappers/librsync_jll.jl/releases/download/librsync-v2.3.4+0/librsync.v2.3.4.x86_64-w64-mingw32.tar.gz"
